# Generated by Django 3.0.5 on 2021-01-06 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetails',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('imei', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.CharField(blank=True, default=1, max_length=500)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_device', to='organisation.Organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devicedetails',
                'verbose_name_plural': 'Devicesdetails',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=150)),
                ('device_type', models.CharField(max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('public_key', models.CharField(blank=True, max_length=2000, null=True, unique=True)),
                ('private_key', models.CharField(blank=True, max_length=2000, null=True, unique=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False, max_length=100)),
                ('authorization_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('authentication_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code_token', models.CharField(max_length=150)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
